### ISSUE TITLE
As a user, I want to be able to enter the location of the place I want to find the shuttle from. 

### ISSUE THREAD

**Issue by Nilesh1603** [cse442-fall-2019-offering/442projects-TheBugSlayers#9]
The user should be able to enter a location in the searchable dropdown menu "Enter Location".

Acceptance Test:
1. I can launch the app from the Expo client and it leads me to the Welcome screen.
2. I am able to enter a location in the searchable dropdown menu "Enter Location".

**Comment by jaskeeratbrar** [comment]
The user is now able to type in a search bar input field.
